\encoding UTF8
DROP TABLE IF EXISTS periods;
DROP TABLE IF EXISTS commas;
DROP TABLE IF EXISTS the;
DROP TABLE IF EXISTS and;

CREATE TABLE periods (
id SERIAL PRIMARY KEY,
count INT NOT NULL
);

CREATE·TABLE·commas·(
id·SERIAL·PRIMARY·KEY,
count·INT·NOT·NULL
);

CREATE·TABLE·the·(
id·SERIAL·PRIMARY·KEY,
count·INT·NOT·NULL
);

CREATE·TABLE·and·(
id·SERIAL·PRIMARY·KEY,
count·INT·NOT·NULL
);
INSERT INTO period (count) VALUES